### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by Matthewkyos** [Rikux3/UsmToolkit#3]
Ran the 
UsmToolkit get-dependencies
and
UsmToolkit convert "file name" 
In command prompt it didn't work
also tried running the .exe file

**Comment by pha1n0q** [comment]
Refer to #1, specifically [this commit](https://github.com/Rikux3/UsmToolkit/pull/1/commits/747d6869e312747d21e56a227345ddcfcaba5dd4) - you can download the dependencies from there.
